spring.application.name=discovery-service
server.port=9999
#don't register server itself as client
#indiquer que ce service n'a pas besoin de récupérer la liste des autres services enregistrés.
eureka.client.fetch-registry=false
#don't register itself in the server register
#indiquer que ce service ne doit pas s?enregistrer dans Eureka.
eureka.client.register-with-eureka=false
