spring.application.name=gateway-service
server.port=8888
#recupirer la config a partir de configservice
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:9999
